# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: author

reviewers:
  - unknowIfGuestInDream
  - DreamAwakenFateBroke

# A number of assignees to add to the pull request
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
numberOfAssignees: 0
numberOfReviewers: 1

skipKeywords:
   - wip
