name: Bug report
description: Create a report to help us improve
title: "[Bug]"
labels:
  - bug
assignees: unknowIfGuestInDream
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |-
        Make sure that you follow these statements.
      options:
        - label: I am using **LTS** version of Java.
          required: true

        - label: I am following the docs and I am sure I am using the correct configuration.
          required: true

  - type: input
    id: package
    attributes:
      label: Package version
      description: which version of the package are you using
      placeholder: package version
    validations:
      required: true

  - type: checkboxes
    id: java-version
    attributes:
      label: which version of java are you using?
      description: You may select more than one.
      options:
        - label: "8"
        - label: "11"
        - label: "17"

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating system are you using?
      description: You may select more than one. Don't select anything if it's not about the environment.
      options:
        - label: macOS
        - label: Windows
        - label: Linux

  - type: markdown
    attributes:
      value: |
        ## Describe the bug

        > If applicable, add screenshots and log to help explain your problem.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: If you are not reporting something obvious, a minial reproductin repo and related log is required.
      placeholder: Add any other context about the problem here. Especially the issue occurs in certain OS, browser or configuation.
