name: General question
description: Ask a question here
title: "[Question]"
labels:
  - question
assignees: unknowIfGuestInDream
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |-
        Make sure that you follow these statements.
      options:
        - label: I am following the docs and I am sure I have tried searching for the problem.
          required: true

  - type: textarea
    id: question
    attributes:
      label: Describe the question
      description: What's it for
      placeholder: write your question here
    validations:
      required: true