name: Generate changelog
on:
  release:
    types: [created, edited]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          ACCESS_TOKEN: ${{secrets.CHANGELOG}}
          PATH: 'CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(changelog): Update release notes'
          TYPE: 'feat:Feature,fix:Bug Fixes,refactor:Refactor,perf:Performance Improvements'
          PULL_REQUEST: 'master'
          BRANCH: 'changelog'
