name: Commit Check

on:
  pull_request:
    branches: 'master'

jobs:
  commit-check:
    runs-on: ubuntu-latest
    permissions: # use permissions because of use pr-comments
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # checkout PR HEAD commit
          fetch-depth: 0  # required for merge-base check
      - uses: commit-check/commit-check-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGELOG }} # use GITHUB_TOKEN because of use pr-comments
        with:
          message: false
          branch: false
          author-name: true
          author-email: true
          commit-signoff: true
          merge-base: false
          job-summary: true
          pr-comments: true
