name: Update CONTRIBUTORS file
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: minicli/action-contributors@v3.3
        name: "Update a projects CONTRIBUTORS file"
        env:
          CONTRIB_REPOSITORY: 'unknowIfGuestInDream/document'
          CONTRIB_OUTPUT_FILE: 'CONTRIBUTORS.md'
          CONTRIB_IGNORE: github-actions[bot],renovate-bot,dependabot,imgbot,deepsourcebot,ImgBotApp
      - name: Create a PR
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          commit-message: Update Contributors
          title: "bot: Update Contributors File"
          token: ${{ secrets.GITHUB_TOKEN }}
          signoff: true
          labels: automerge
