name: 'Dependency Review'
on:
  pull_request:
    branches: [ 'master' ]
    paths:
      - 'pom.xml'
      - '**/pom.xml'

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v5
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          fail-on-scopes: runtime, development
          license-check: true
          comment-summary-in-pr: true
          # https://spdx.org/licenses/
          deny-licenses: GPL-1.0, GPL-2.0, AGPL-1.0, AGPL-3.0
