name: Deploy javadoc
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.github/workflows/**'
      - '.idea/**'
      - '.settings/**'
      - '.vscode/**'
      - 'README*.md'
      - '.gitignore'
      - '.editorconfig'
      - '.gitattributes'
      - '.mergify.yml'
      - 'CHANGELOG.md'
      - 'CONTRIBUTORS.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'qodana.yaml'
      - 'sweep.yaml'
      - 'SECURITY.md'
      - '.imgbotconfig'
      - 'core/src/main/java/com/tlcsdm/core/util/DependencyInfo.java'
      - 'docs/**'
      - '*/src/test/**'
      - 'Jenkinsfile'

jobs:
  deployJavadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Generate javadoc
        run: mvn -B --file pom.xml -DskipTests javadoc:aggregate-jar
      - name: Publish to server
        uses: easingthemes/ssh-deploy@v5.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "target/reports/apidocs/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.JAVADOC_TARGET }}
