name: Doxygen

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    env:
      PLANTUML_JAR_PATH: /usr/share/plantuml/plantuml.jar

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Doxygen, Graphviz and PlantUML
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq doxygen graphviz plantuml

      - name: Generate documentation
        run: doxygen doxygen/Doxyfile

      - name: Upload documentation
        uses: actions/upload-artifact@v7
        with:
          name: doxygen-docs
          path: docs-gen/html
          retention-days: 14
