name: jDeploy CI with Maven

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --file pom.xml -DskipTests -Duser.name='Github Action' package
      - name: Build App Installer Bundles
        uses: shannah/jdeploy@master
        with:
          target_repository: 'shannah/jdeploy-javafx-starter-releases'
          github_token: ${{ secrets.GITHUB_TOKEN }}
